name: Run API Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Testes com Jest
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Clonar reposit칩rio
        uses: actions/checkout@v4

      - name: 游릭 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ou a vers칚o que sua API usa

      - name: 游닍 Instalar depend칡ncias
        run: npm ci  # mais r치pido e seguro que `npm install` em CI

      - name: 游빍 Executar testes com Jest
        run: npm test -- --coverage
        env:
          CI: true
